# UNIVERSAL FUNCTION 

In [1]:
import numpy as np

In [2]:
a=np.array([1,4,9,16,25,36,49,64,81,100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [3]:
np.sin(a)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [4]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.cos(a)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281,
       -0.12796369,  0.30059254,  0.39185723,  0.77668598,  0.86231887])

In [6]:
np.log(a)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

In [7]:
from numpy import pi

In [8]:
np.sin(pi/2)

1.0

# FLOOR AND CEIL

In [9]:
a=np.array([12.34,3.25,15.67,-9.17])
np.floor(a)

array([ 12.,   3.,  15., -10.])

In [10]:
np.ceil(a)

array([13.,  4., 16., -9.])

# SHAPE MANUPULATION:

RESHAPE: It gives us new array without changing its orignal array.

RESIZE: It directly changes the orignal array.

RAVEL: It converts array into 1D array.

FLATTEN: It also converts array into 1D array and it is a normal function not numpy functions.

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.resize(arr,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
a=np.array([[1,2,3],[4,5,6]])

In [14]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b=a.flatten()
b

array([1, 2, 3, 4, 5, 6])

In [17]:
d= lambda c: (9/5)*c+32
d(30)

86.0

In [18]:
c=lambda a,b : a**b

In [24]:
c(34,5)

39

In [25]:
np.fromfunction(lambda x,y: x+y,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [26]:
np.fromiter([1,2,3,4,5,6],dtype=float)

array([1., 2., 3., 4., 5., 6.])

In [27]:
np.fromstring('1 2 3 4 5 6',sep= ' ', dtype=int)
#It only takes number

array([1, 2, 3, 4, 5, 6])

In [28]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])