# SHAPE MANUPULATION:

RESHAPE: It gives us new array without changing its orignal array.

RESIZE: It directly changes the orignal array.

RAVEL: It converts array into 1D array.

FLATTEN: It also converts array into 1D array and it is a normal function not numpy functions.

In [1]:
import numpy as np

In [2]:
number=np.ones((3,3))
number

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.diag(a, k=0) #by default k=0

array([1, 5, 9])

In [10]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [12]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [13]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [14]:
np.diagflat([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
np.arange(11.2,2,-1.2)

array([11.2, 10. ,  8.8,  7.6,  6.4,  5.2,  4. ,  2.8])

In [16]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
np.logspace(1,5,20)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.trace(a) #trace command is used to make the sum of diagonal 

15

# Random number generation using numpy

In [22]:
from numpy import random

In [23]:
a=np.random.rand(3,3)
a

array([[0.67979859, 0.7768    , 0.14589013],
       [0.1859519 , 0.74561723, 0.64071256],
       [0.80832049, 0.24078061, 0.76794966]])

In [26]:
b=np.random.randint(10,100,(4,4))
b

array([[98, 97, 21, 65],
       [80, 74, 38, 26],
       [35, 39, 82, 33],
       [34, 60, 98, 25]])

In [27]:
np.random.randn(2,2)

array([[-0.59535934,  0.5189112 ],
       [-0.81639143,  0.96925838]])

In [29]:
c=np.random.randint(10,100,(3,3))
c

array([[94, 34, 94],
       [54, 29, 71],
       [63, 95, 19]])

In [32]:
c.sort(axis=1) # axis=1 is for row
c

array([[19, 54, 71],
       [29, 63, 94],
       [34, 94, 95]])

In [33]:
c.sort(axis=0)   # axis=0 is for column
c

array([[19, 54, 71],
       [29, 63, 94],
       [34, 94, 95]])

In [34]:
c.max()

95

In [35]:
c.min()

19

In [36]:
np.argmax(c)

8

In [37]:
np.argmin(c)

0

In [38]:
np.cumsum([1,2,3,4,5,6,7,8,9])

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])