# NUMPY CONCEPT-1

NUMPY:

It stands for Numercal Python. Numpy is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrix.

In [1]:
d=[10,20,30,40]
t=[2,3,4,5]
s=d/t
print(s) #For this reason we use numpy 

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [2]:
import numpy as np

In [3]:
d= np.array([10,20,30,40])
t=np.array([2,3,4,5])
s=d/t
print("speed : ", s)

speed :  [5.         6.66666667 7.5        8.        ]


ND araay:

This means number of dimensions in the given array and is decided by number of list brackets in it.

In [4]:
x= ([1,2,3],[2,3,4],[3,4,5])
arr = np.array(x)
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [6]:
#slicing in the array
arr[2][0]

3

In [7]:
# how to know the shape of any array

arr.shape

(3, 3)

In [8]:
# How to know the size of any array

arr.size

9

In [9]:
# To know the dtype

arr.dtype

dtype('int32')

What happens when two array is added?

In [11]:
a=np.array([10,11,12,13,14])
b=np.array([5,6,7,8,9])
add=a+b
add

array([15, 17, 19, 21, 23])

Multiplication the sum of two array with 2?

In [12]:
a=np.array([[1,2,3],[4,2,4]])
b=np.array([[6,7,8],[5,8,9]])
(a+b)*2

array([[14, 18, 22],
       [18, 20, 26]])