# OPERATIONS IN NUMPY :

In [2]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [5]:
arr[1][1]=50
arr

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [6]:
arr=np.array(arr,dtype=float)
arr

array([[ 1.,  2.,  3.],
       [ 4., 50.,  6.],
       [ 7.,  8.,  9.]])

In [7]:
arr=np.array([[90,86,67,50,55,49],[64,88,82,45,69,52]])
arr

array([[90, 86, 67, 50, 55, 49],
       [64, 88, 82, 45, 69, 52]])

In [8]:
passing_marks=50

In [9]:
arr[arr>passing_marks]

array([90, 86, 67, 55, 64, 88, 82, 69, 52])

Q). WAP To create two arrays of distance covered by two cycles, add them up to get the array total distance travelled. iif the distance is greater than 30. filter those values only and array should be of (1x3)?

In [10]:
cycle1=np.array([10,20,30])
cycle2=np.array([10,30,10])
arr=cycle1+cycle2
arr


array([20, 50, 40])

In [11]:
arr>30

array([False,  True,  True])

In [13]:
s=np.array([['Delhi','Mumbai','Pune','Indore','Chennai'],['Delhi','maha','Maha','mp','Tamil nadu']])
s

array([['Delhi', 'Mumbai', 'Pune', 'Indore', 'Chennai'],
       ['Delhi', 'maha', 'Maha', 'mp', 'Tamil nadu']], dtype='<U10')

In [14]:
s[0:2,1:3]

array([['Mumbai', 'Pune'],
       ['maha', 'Maha']], dtype='<U10')

In [15]:
s[:,3:][1][0]

'mp'

Q).WAP tp create a 3x3 array. Then slice it as we want 1,2 row and 1,2 column. After slicing check which elements of sliced array is div by 3?

In [16]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b=a[1:3,1:3]

In [18]:
b[b%3==0]

array([6, 9])

In [19]:
b[b%3==0].sum()

15

In [20]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [21]:
l=[]
for i in a:
    for j in i:
        l.append(j)
        
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
m=np.array([[[1,2,3,4,5,6,7,8,9,10]]])
m[0][0][5]

6

In [23]:
b1=b.copy()
b1[1][1]=90
b1

array([[ 5,  6],
       [ 8, 90]])

In [24]:
b

array([[5, 6],
       [8, 9]])